---

- name: copy start up script to destination hosts
  copy: src={{item}} dest={{tmpworkspace}} owner=BigData mode=777
  with_items:
    - starthadoop.sh
    - startspark.sh

- name: yml start hadoop service 
  shell: /tmp/starthadoop.sh executable=/bin/bash

- name: yml start spark service
  shell: /tmp/startspark.sh executable=/bin/bash

- name: clear tmp resource
  command: rm -rf {{tmpworkspace}}/starthadoop.sh {{tmpworkspace}}/startspark.sh

